export const COLLECTIONS = {
  GET_COLLECTIONS: 'COLLECTIONS.GET_COLLECTIONS'
}

export const LABELS = {
  GET_LABELS: 'LABELS.GET_LABELS'
}

export const QUEUE = {
  ADD_LABELS: 'QUEUE.ADD_LABELS',
  ADD_LABEL: 'QUEUE.ADD_LABEL',
  REMOVE_ALL_LABELS: 'QUEUE.REMOVE_ALL_LABELS',
  REMOVE_LABEL: 'QUEUE.REMOVE_LABEL',
  UPDATE_QUANTITY: 'QUEUE.UPDATE_QUANTITY'
}
